---
# Dashboard prerequisites
- name: Remove invalid PHP .ini file
  file: path=/etc/php/{{ dashboard_php_major_minor_version }}/fpm/conf.d/20-pcntl.ini state=absent

- name: Copying Dashboard configuration for Nginx
  template:
    src: "dashboard.nginx.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  notify:
    - reload nginx

- name: Installing required packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-client
    - php{{ dashboard_php_major_minor_version }}-zip

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Empty shared folder to free up space
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ project_shared_path }}"
