---
# Dashboard prerequisites
- name: Enable the PHP pcntl extension
  copy:
    content: |-
      extension=pcntl.so
    dest: /etc/php/{{ dashboard_php_major_minor_version }}/fpm/conf.d/20-pcntl.ini
    owner: root
    group: root
    mode: 0644

# Dashboard prerequisites
- name: Copying Dashboard configuration for Nginx
  template:
    src: "dashboard.nginx.conf"
    dest: "/etc/nginx/sites-enabled/dashboard.nginx.conf"
  notify:
    - reload nginx

- name: Installing required packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-client
    - php{{ dashboard_php_major_minor_version }}-zip
    - nginx-extras

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Empty shared folder to free up space
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ project_shared_path }}"
