---
# Dashboard prerequisites

- name: Copying Dashboard configuration for Nginx
  template:
    src: "dashboard.nginx.conf"
    dest: "/etc/nginx/sites-enabled/dashboard.nginx.conf"
  notify:
    - reload nginx

# TODO use the host tls certificate
- name: Copy SAML crt
  copy:
    content: |-
      {{ saml2_sp_public_certificate }}
    dest: "{{ saml_sp_cert_path }}"
    owner: root
    group: ssl-cert
    mode: 0644

# TODO use the host tls key
- name: Copy SAML key
  copy:
    content: |-
      {{ saml2_sp_private_key }}
    dest: "{{ saml_sp_private_key_path }}"
    owner: root
    group: ssl-cert
    mode: 0640

- name: Installing required packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-client
    - php{{ php_major_minor_version }}-zip
    - nginx-extras

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Empty shared folder to free up space
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ project_shared_path }}"
