---
- name: supervisor reload
  shell: supervisorctl reread && supervisorctl update
  become: yes
  tags:
    - skip_ansible_lint

- name: restart php-fpm
  service: name=php{{ dashboard_php_major_minor_version }}-fpm state=restarted

- name: reload nginx
  service: name=nginx state=reloaded
