---
- name: Prepare
  hosts: all
  vars:
    php_version: "7.3"
    php_default_version_debian: "7.3"
  pre_tasks:
    - name: Add repository for PHP
      apt_repository:
        repo: "ppa:ondrej/php"
      register: ppa
    - name: Update Apt
      apt: update_cache=yes
      when: ppa is changed

  roles:
    - role: geerlingguy.nginx
    - role: geerlingguy.php
      php_webserver_daemon: nginx
    - role: geerlingguy.composer

  tasks:
    - name: Create ubuntu user
      user: name=ubuntu state=present

    - name: Install OS dependencies
      apt: name={{ packages }} state=present update_cache=yes cache_valid_time={{ 24 * 60 * 60 }}
      vars:
        packages:
          - cron
          - git
          - supervisor

    - name: Start supervisor
      service: name=supervisor state=started enabled=true
